fragment OmOssParts on OmOss {
  __typename
  title
  description
  blocks {
    __typename
    ... on OmOssBlocksAbout {
      title
      body
      image
      video
    }
    ... on OmOssBlocksValues {
      title
      description
      variant
      image
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on OmOssBlocksMembership {
      title
      description
      linkUrl
      boostLinkUrl
      boostEnabled
      extraInfo
    }
    ... on OmOssBlocksTrainers {
      title
      trainerList {
        __typename
        name
        role
        image
        bio
      }
    }
    ... on OmOssBlocksSponsors {
      title
      sponsorList {
        __typename
        name
        logo
        url
      }
    }
    ... on OmOssBlocksBenefits {
      title
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on OmOssBlocksFaq {
      title
      items {
        __typename
        question
        answer
      }
    }
    ... on OmOssBlocksPackages {
      title
      description
      packagesList {
        __typename
        name
        description
        perks
        highlighted
      }
    }
    ... on OmOssBlocksTimeline {
      title
      subtitle
      events {
        __typename
        year
        title
        location
        description
        highlight
      }
    }
    ... on OmOssBlocksOrgSeparation {
      title
      subtitle
      description
    }
    ... on OmOssBlocksCheckmat {
      title
      subtitle
      description
      features {
        __typename
        title
        description
        icon
      }
    }
  }
}

fragment PageParts on Page {
  __typename
  title
  description
  blocks {
    __typename
    ... on PageBlocksAbout {
      title
      body
      image
      video
    }
    ... on PageBlocksValues {
      title
      description
      variant
      image
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on PageBlocksMembership {
      title
      description
      linkUrl
      boostLinkUrl
      boostEnabled
      extraInfo
    }
    ... on PageBlocksTrainers {
      title
      trainerList {
        __typename
        name
        role
        image
        bio
      }
    }
    ... on PageBlocksSponsors {
      title
      sponsorList {
        __typename
        name
        logo
        url
      }
    }
    ... on PageBlocksBenefits {
      title
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on PageBlocksFaq {
      title
      items {
        __typename
        question
        answer
      }
    }
    ... on PageBlocksPackages {
      title
      description
      packagesList {
        __typename
        name
        description
        perks
        highlighted
      }
    }
    ... on PageBlocksTimeline {
      title
      subtitle
      events {
        __typename
        year
        title
        location
        description
        highlight
      }
    }
    ... on PageBlocksOrgSeparation {
      title
      subtitle
      description
    }
    ... on PageBlocksCheckmat {
      title
      subtitle
      description
      features {
        __typename
        title
        description
        icon
      }
    }
  }
}

fragment HeroParts on Hero {
  __typename
  welcomeText
  highlightedText
  description
  backgroundImage
  backgroundVideo
  instagramTitle
  instagramUsername
  instagramLink
  instagramImages {
    __typename
    image
    caption
    postUrl
  }
}

fragment ScheduleParts on Schedule {
  __typename
  days {
    __typename
    day
    slots {
      __typename
      time
      activity
      group
      room
      trainer
    }
  }
}

fragment StyretParts on Styret {
  __typename
  title
  description
  blocks {
    __typename
    ... on StyretBlocksAbout {
      title
      body
      image
      video
    }
    ... on StyretBlocksValues {
      title
      description
      variant
      image
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on StyretBlocksMembership {
      title
      description
      linkUrl
      boostLinkUrl
      boostEnabled
      extraInfo
    }
    ... on StyretBlocksTrainers {
      title
      trainerList {
        __typename
        name
        role
        image
        bio
      }
    }
    ... on StyretBlocksSponsors {
      title
      sponsorList {
        __typename
        name
        logo
        url
      }
    }
    ... on StyretBlocksBenefits {
      title
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on StyretBlocksFaq {
      title
      items {
        __typename
        question
        answer
      }
    }
    ... on StyretBlocksPackages {
      title
      description
      packagesList {
        __typename
        name
        description
        perks
        highlighted
      }
    }
    ... on StyretBlocksTimeline {
      title
      subtitle
      events {
        __typename
        year
        title
        location
        description
        highlight
      }
    }
    ... on StyretBlocksOrgSeparation {
      title
      subtitle
      description
    }
    ... on StyretBlocksCheckmat {
      title
      subtitle
      description
      features {
        __typename
        title
        description
        icon
      }
    }
  }
  members {
    __typename
    role
    name
    image
  }
  committees {
    __typename
    name
    people {
      __typename
      role
      name
    }
  }
}

fragment OrganisasjonsplanParts on Organisasjonsplan {
  __typename
  title
  body
}

fragment NewsParts on News {
  __typename
  title
  date
  category
  image
  description
  body
}

fragment SponsorerParts on Sponsorer {
  __typename
  title
  blocks {
    __typename
    ... on SponsorerBlocksAbout {
      title
      body
      image
      video
    }
    ... on SponsorerBlocksValues {
      title
      description
      variant
      image
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on SponsorerBlocksMembership {
      title
      description
      linkUrl
      boostLinkUrl
      boostEnabled
      extraInfo
    }
    ... on SponsorerBlocksTrainers {
      title
      trainerList {
        __typename
        name
        role
        image
        bio
      }
    }
    ... on SponsorerBlocksSponsors {
      title
      sponsorList {
        __typename
        name
        logo
        url
      }
    }
    ... on SponsorerBlocksBenefits {
      title
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on SponsorerBlocksFaq {
      title
      items {
        __typename
        question
        answer
      }
    }
    ... on SponsorerBlocksPackages {
      title
      description
      packagesList {
        __typename
        name
        description
        perks
        highlighted
      }
    }
    ... on SponsorerBlocksTimeline {
      title
      subtitle
      events {
        __typename
        year
        title
        location
        description
        highlight
      }
    }
    ... on SponsorerBlocksOrgSeparation {
      title
      subtitle
      description
    }
    ... on SponsorerBlocksCheckmat {
      title
      subtitle
      description
      features {
        __typename
        title
        description
        icon
      }
    }
  }
}

fragment MedlemskapParts on Medlemskap {
  __typename
  title
  blocks {
    __typename
    ... on MedlemskapBlocksAbout {
      title
      body
      image
      video
    }
    ... on MedlemskapBlocksValues {
      title
      description
      variant
      image
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on MedlemskapBlocksMembership {
      title
      description
      linkUrl
      boostLinkUrl
      boostEnabled
      extraInfo
    }
    ... on MedlemskapBlocksTrainers {
      title
      trainerList {
        __typename
        name
        role
        image
        bio
      }
    }
    ... on MedlemskapBlocksSponsors {
      title
      sponsorList {
        __typename
        name
        logo
        url
      }
    }
    ... on MedlemskapBlocksBenefits {
      title
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on MedlemskapBlocksFaq {
      title
      items {
        __typename
        question
        answer
      }
    }
    ... on MedlemskapBlocksPackages {
      title
      description
      packagesList {
        __typename
        name
        description
        perks
        highlighted
      }
    }
    ... on MedlemskapBlocksTimeline {
      title
      subtitle
      events {
        __typename
        year
        title
        location
        description
        highlight
      }
    }
    ... on MedlemskapBlocksOrgSeparation {
      title
      subtitle
      description
    }
    ... on MedlemskapBlocksCheckmat {
      title
      subtitle
      description
      features {
        __typename
        title
        description
        icon
      }
    }
  }
}

fragment ContactParts on Contact {
  __typename
  email
  phone
  address
  facebook
  instagram
  image
}

fragment GlobalParts on Global {
  __typename
  clubName
  logo
  facebook
  instagram
  nav {
    __typename
    label
    href
  }
  sponsors {
    __typename
    name
    logo
    url
  }
  footerDescription
  footerEmail
  footerPhone
  footerAddress
  footerOrgNumber
}
