//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
  hero: Hero;
  heroConnection: HeroConnection;
  styret: Styret;
  styretConnection: StyretConnection;
  organisasjonsplan: Organisasjonsplan;
  organisasjonsplanConnection: OrganisasjonsplanConnection;
  news: News;
  newsConnection: NewsConnection;
  sponsorer: Sponsorer;
  sponsorerConnection: SponsorerConnection;
  medlemskap: Medlemskap;
  medlemskapConnection: MedlemskapConnection;
  omOss: OmOss;
  omOssConnection: OmOssConnection;
  contact: Contact;
  contactConnection: ContactConnection;
  global: Global;
  globalConnection: GlobalConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryHeroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
};


export type QueryStyretArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStyretConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StyretFilter>;
};


export type QueryOrganisasjonsplanArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOrganisasjonsplanConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OrganisasjonsplanFilter>;
};


export type QueryNewsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNewsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
};


export type QuerySponsorerArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySponsorerConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SponsorerFilter>;
};


export type QueryMedlemskapArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMedlemskapConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MedlemskapFilter>;
};


export type QueryOmOssArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOmOssConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OmOssFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};


export type QueryGlobalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
  hero?: InputMaybe<HeroFilter>;
  styret?: InputMaybe<StyretFilter>;
  organisasjonsplan?: InputMaybe<OrganisasjonsplanFilter>;
  news?: InputMaybe<NewsFilter>;
  sponsorer?: InputMaybe<SponsorerFilter>;
  medlemskap?: InputMaybe<MedlemskapFilter>;
  omOss?: InputMaybe<OmOssFilter>;
  contact?: InputMaybe<ContactFilter>;
  global?: InputMaybe<GlobalFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Hero | Styret | Organisasjonsplan | News | Sponsorer | Medlemskap | OmOss | Contact | Global | Folder;

export type PageBlocksAbout = {
  __typename?: 'PageBlocksAbout';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksValuesItems = {
  __typename?: 'PageBlocksValuesItems';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksValues = {
  __typename?: 'PageBlocksValues';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  variant?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PageBlocksValuesItems>>>;
};

export type PageBlocksMembership = {
  __typename?: 'PageBlocksMembership';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  linkUrl?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksTrainersTrainerList = {
  __typename?: 'PageBlocksTrainersTrainerList';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksTrainers = {
  __typename?: 'PageBlocksTrainers';
  title?: Maybe<Scalars['String']['output']>;
  trainerList?: Maybe<Array<Maybe<PageBlocksTrainersTrainerList>>>;
};

export type PageBlocksSponsorsSponsorList = {
  __typename?: 'PageBlocksSponsorsSponsorList';
  name?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksSponsors = {
  __typename?: 'PageBlocksSponsors';
  title?: Maybe<Scalars['String']['output']>;
  sponsorList?: Maybe<Array<Maybe<PageBlocksSponsorsSponsorList>>>;
};

export type PageBlocksBenefitsItems = {
  __typename?: 'PageBlocksBenefitsItems';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksBenefits = {
  __typename?: 'PageBlocksBenefits';
  title?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PageBlocksBenefitsItems>>>;
};

export type PageBlocks = PageBlocksAbout | PageBlocksValues | PageBlocksMembership | PageBlocksTrainers | PageBlocksSponsors | PageBlocksBenefits;

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  blocks?: Maybe<Array<Maybe<PageBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageBlocksAboutFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type PageBlocksValuesItemsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type PageBlocksValuesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  items?: InputMaybe<PageBlocksValuesItemsFilter>;
};

export type PageBlocksMembershipFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  linkUrl?: InputMaybe<StringFilter>;
};

export type PageBlocksTrainersTrainerListFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<StringFilter>;
};

export type PageBlocksTrainersFilter = {
  title?: InputMaybe<StringFilter>;
  trainerList?: InputMaybe<PageBlocksTrainersTrainerListFilter>;
};

export type PageBlocksSponsorsSponsorListFilter = {
  name?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  url?: InputMaybe<StringFilter>;
};

export type PageBlocksSponsorsFilter = {
  title?: InputMaybe<StringFilter>;
  sponsorList?: InputMaybe<PageBlocksSponsorsSponsorListFilter>;
};

export type PageBlocksBenefitsItemsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type PageBlocksBenefitsFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<PageBlocksBenefitsItemsFilter>;
};

export type PageBlocksFilter = {
  about?: InputMaybe<PageBlocksAboutFilter>;
  values?: InputMaybe<PageBlocksValuesFilter>;
  membership?: InputMaybe<PageBlocksMembershipFilter>;
  trainers?: InputMaybe<PageBlocksTrainersFilter>;
  sponsors?: InputMaybe<PageBlocksSponsorsFilter>;
  benefits?: InputMaybe<PageBlocksBenefitsFilter>;
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<PageBlocksFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Hero = Node & Document & {
  __typename?: 'Hero';
  welcomeText?: Maybe<Scalars['String']['output']>;
  highlightedText?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
  backgroundVideo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HeroFilter = {
  welcomeText?: InputMaybe<StringFilter>;
  highlightedText?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
  backgroundVideo?: InputMaybe<ImageFilter>;
};

export type HeroConnectionEdges = {
  __typename?: 'HeroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hero>;
};

export type HeroConnection = Connection & {
  __typename?: 'HeroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeroConnectionEdges>>>;
};

export type StyretBlocksAbout = {
  __typename?: 'StyretBlocksAbout';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type StyretBlocks = StyretBlocksAbout;

export type StyretMembers = {
  __typename?: 'StyretMembers';
  role?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type StyretCommitteesPeople = {
  __typename?: 'StyretCommitteesPeople';
  role?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
};

export type StyretCommittees = {
  __typename?: 'StyretCommittees';
  name?: Maybe<Scalars['String']['output']>;
  people?: Maybe<Array<Maybe<StyretCommitteesPeople>>>;
};

export type Styret = Node & Document & {
  __typename?: 'Styret';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
  blocks?: Maybe<Array<Maybe<StyretBlocks>>>;
  members?: Maybe<Array<Maybe<StyretMembers>>>;
  committees?: Maybe<Array<Maybe<StyretCommittees>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type StyretBlocksAboutFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type StyretBlocksFilter = {
  about?: InputMaybe<StyretBlocksAboutFilter>;
};

export type StyretMembersFilter = {
  role?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type StyretCommitteesPeopleFilter = {
  role?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
};

export type StyretCommitteesFilter = {
  name?: InputMaybe<StringFilter>;
  people?: InputMaybe<StyretCommitteesPeopleFilter>;
};

export type StyretFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  blocks?: InputMaybe<StyretBlocksFilter>;
  members?: InputMaybe<StyretMembersFilter>;
  committees?: InputMaybe<StyretCommitteesFilter>;
};

export type StyretConnectionEdges = {
  __typename?: 'StyretConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Styret>;
};

export type StyretConnection = Connection & {
  __typename?: 'StyretConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StyretConnectionEdges>>>;
};

export type Organisasjonsplan = Node & Document & {
  __typename?: 'Organisasjonsplan';
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OrganisasjonsplanFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type OrganisasjonsplanConnectionEdges = {
  __typename?: 'OrganisasjonsplanConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Organisasjonsplan>;
};

export type OrganisasjonsplanConnection = Connection & {
  __typename?: 'OrganisasjonsplanConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OrganisasjonsplanConnectionEdges>>>;
};

export type News = Node & Document & {
  __typename?: 'News';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NewsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type NewsConnectionEdges = {
  __typename?: 'NewsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<News>;
};

export type NewsConnection = Connection & {
  __typename?: 'NewsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NewsConnectionEdges>>>;
};

export type SponsorerBlocksAbout = {
  __typename?: 'SponsorerBlocksAbout';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type SponsorerBlocksBenefitsItems = {
  __typename?: 'SponsorerBlocksBenefitsItems';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type SponsorerBlocksBenefits = {
  __typename?: 'SponsorerBlocksBenefits';
  title?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<SponsorerBlocksBenefitsItems>>>;
};

export type SponsorerBlocksSponsorsSponsorList = {
  __typename?: 'SponsorerBlocksSponsorsSponsorList';
  name?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type SponsorerBlocksSponsors = {
  __typename?: 'SponsorerBlocksSponsors';
  title?: Maybe<Scalars['String']['output']>;
  sponsorList?: Maybe<Array<Maybe<SponsorerBlocksSponsorsSponsorList>>>;
};

export type SponsorerBlocks = SponsorerBlocksAbout | SponsorerBlocksBenefits | SponsorerBlocksSponsors;

export type Sponsorer = Node & Document & {
  __typename?: 'Sponsorer';
  title: Scalars['String']['output'];
  blocks?: Maybe<Array<Maybe<SponsorerBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SponsorerBlocksAboutFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type SponsorerBlocksBenefitsItemsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type SponsorerBlocksBenefitsFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<SponsorerBlocksBenefitsItemsFilter>;
};

export type SponsorerBlocksSponsorsSponsorListFilter = {
  name?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  url?: InputMaybe<StringFilter>;
};

export type SponsorerBlocksSponsorsFilter = {
  title?: InputMaybe<StringFilter>;
  sponsorList?: InputMaybe<SponsorerBlocksSponsorsSponsorListFilter>;
};

export type SponsorerBlocksFilter = {
  about?: InputMaybe<SponsorerBlocksAboutFilter>;
  benefits?: InputMaybe<SponsorerBlocksBenefitsFilter>;
  sponsors?: InputMaybe<SponsorerBlocksSponsorsFilter>;
};

export type SponsorerFilter = {
  title?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<SponsorerBlocksFilter>;
};

export type SponsorerConnectionEdges = {
  __typename?: 'SponsorerConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Sponsorer>;
};

export type SponsorerConnection = Connection & {
  __typename?: 'SponsorerConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SponsorerConnectionEdges>>>;
};

export type MedlemskapBlocksMembership = {
  __typename?: 'MedlemskapBlocksMembership';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  linkUrl?: Maybe<Scalars['String']['output']>;
  extraInfo?: Maybe<Scalars['String']['output']>;
};

export type MedlemskapBlocksAbout = {
  __typename?: 'MedlemskapBlocksAbout';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type MedlemskapBlocks = MedlemskapBlocksMembership | MedlemskapBlocksAbout;

export type Medlemskap = Node & Document & {
  __typename?: 'Medlemskap';
  title: Scalars['String']['output'];
  blocks?: Maybe<Array<Maybe<MedlemskapBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MedlemskapBlocksMembershipFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  linkUrl?: InputMaybe<StringFilter>;
  extraInfo?: InputMaybe<StringFilter>;
};

export type MedlemskapBlocksAboutFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type MedlemskapBlocksFilter = {
  membership?: InputMaybe<MedlemskapBlocksMembershipFilter>;
  about?: InputMaybe<MedlemskapBlocksAboutFilter>;
};

export type MedlemskapFilter = {
  title?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<MedlemskapBlocksFilter>;
};

export type MedlemskapConnectionEdges = {
  __typename?: 'MedlemskapConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Medlemskap>;
};

export type MedlemskapConnection = Connection & {
  __typename?: 'MedlemskapConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MedlemskapConnectionEdges>>>;
};

export type OmOssBlocksAbout = {
  __typename?: 'OmOssBlocksAbout';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  video?: Maybe<Scalars['String']['output']>;
};

export type OmOssBlocksValuesItems = {
  __typename?: 'OmOssBlocksValuesItems';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type OmOssBlocksValues = {
  __typename?: 'OmOssBlocksValues';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  variant?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<OmOssBlocksValuesItems>>>;
};

export type OmOssBlocksTrainersTrainerList = {
  __typename?: 'OmOssBlocksTrainersTrainerList';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
};

export type OmOssBlocksTrainers = {
  __typename?: 'OmOssBlocksTrainers';
  title?: Maybe<Scalars['String']['output']>;
  trainerList?: Maybe<Array<Maybe<OmOssBlocksTrainersTrainerList>>>;
};

export type OmOssBlocks = OmOssBlocksAbout | OmOssBlocksValues | OmOssBlocksTrainers;

export type OmOss = Node & Document & {
  __typename?: 'OmOss';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  blocks?: Maybe<Array<Maybe<OmOssBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OmOssBlocksAboutFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  video?: InputMaybe<ImageFilter>;
};

export type OmOssBlocksValuesItemsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type OmOssBlocksValuesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  variant?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  items?: InputMaybe<OmOssBlocksValuesItemsFilter>;
};

export type OmOssBlocksTrainersTrainerListFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<StringFilter>;
};

export type OmOssBlocksTrainersFilter = {
  title?: InputMaybe<StringFilter>;
  trainerList?: InputMaybe<OmOssBlocksTrainersTrainerListFilter>;
};

export type OmOssBlocksFilter = {
  about?: InputMaybe<OmOssBlocksAboutFilter>;
  values?: InputMaybe<OmOssBlocksValuesFilter>;
  trainers?: InputMaybe<OmOssBlocksTrainersFilter>;
};

export type OmOssFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<OmOssBlocksFilter>;
};

export type OmOssConnectionEdges = {
  __typename?: 'OmOssConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<OmOss>;
};

export type OmOssConnection = Connection & {
  __typename?: 'OmOssConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OmOssConnectionEdges>>>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  facebook?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactFilter = {
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type GlobalNav = {
  __typename?: 'GlobalNav';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type Global = Node & Document & {
  __typename?: 'Global';
  clubName?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  nav?: Maybe<Array<Maybe<GlobalNav>>>;
  footerDescription?: Maybe<Scalars['String']['output']>;
  footerEmail?: Maybe<Scalars['String']['output']>;
  footerPhone?: Maybe<Scalars['String']['output']>;
  footerAddress?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlobalNavFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type GlobalFilter = {
  clubName?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  nav?: InputMaybe<GlobalNavFilter>;
  footerDescription?: InputMaybe<StringFilter>;
  footerEmail?: InputMaybe<StringFilter>;
  footerPhone?: InputMaybe<StringFilter>;
  footerAddress?: InputMaybe<StringFilter>;
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Global>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePage: Page;
  createPage: Page;
  updateHero: Hero;
  createHero: Hero;
  updateStyret: Styret;
  createStyret: Styret;
  updateOrganisasjonsplan: Organisasjonsplan;
  createOrganisasjonsplan: Organisasjonsplan;
  updateNews: News;
  createNews: News;
  updateSponsorer: Sponsorer;
  createSponsorer: Sponsorer;
  updateMedlemskap: Medlemskap;
  createMedlemskap: Medlemskap;
  updateOmOss: OmOss;
  createOmOss: OmOss;
  updateContact: Contact;
  createContact: Contact;
  updateGlobal: Global;
  createGlobal: Global;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationCreateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationUpdateStyretArgs = {
  relativePath: Scalars['String']['input'];
  params: StyretMutation;
};


export type MutationCreateStyretArgs = {
  relativePath: Scalars['String']['input'];
  params: StyretMutation;
};


export type MutationUpdateOrganisasjonsplanArgs = {
  relativePath: Scalars['String']['input'];
  params: OrganisasjonsplanMutation;
};


export type MutationCreateOrganisasjonsplanArgs = {
  relativePath: Scalars['String']['input'];
  params: OrganisasjonsplanMutation;
};


export type MutationUpdateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationCreateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationUpdateSponsorerArgs = {
  relativePath: Scalars['String']['input'];
  params: SponsorerMutation;
};


export type MutationCreateSponsorerArgs = {
  relativePath: Scalars['String']['input'];
  params: SponsorerMutation;
};


export type MutationUpdateMedlemskapArgs = {
  relativePath: Scalars['String']['input'];
  params: MedlemskapMutation;
};


export type MutationCreateMedlemskapArgs = {
  relativePath: Scalars['String']['input'];
  params: MedlemskapMutation;
};


export type MutationUpdateOmOssArgs = {
  relativePath: Scalars['String']['input'];
  params: OmOssMutation;
};


export type MutationCreateOmOssArgs = {
  relativePath: Scalars['String']['input'];
  params: OmOssMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationUpdateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationCreateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  hero?: InputMaybe<HeroMutation>;
  styret?: InputMaybe<StyretMutation>;
  organisasjonsplan?: InputMaybe<OrganisasjonsplanMutation>;
  news?: InputMaybe<NewsMutation>;
  sponsorer?: InputMaybe<SponsorerMutation>;
  medlemskap?: InputMaybe<MedlemskapMutation>;
  omOss?: InputMaybe<OmOssMutation>;
  contact?: InputMaybe<ContactMutation>;
  global?: InputMaybe<GlobalMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
  hero?: InputMaybe<HeroMutation>;
  styret?: InputMaybe<StyretMutation>;
  organisasjonsplan?: InputMaybe<OrganisasjonsplanMutation>;
  news?: InputMaybe<NewsMutation>;
  sponsorer?: InputMaybe<SponsorerMutation>;
  medlemskap?: InputMaybe<MedlemskapMutation>;
  omOss?: InputMaybe<OmOssMutation>;
  contact?: InputMaybe<ContactMutation>;
  global?: InputMaybe<GlobalMutation>;
};

export type PageBlocksAboutMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksValuesItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksValuesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  variant?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PageBlocksValuesItemsMutation>>>;
};

export type PageBlocksMembershipMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  linkUrl?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksTrainersTrainerListMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksTrainersMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  trainerList?: InputMaybe<Array<InputMaybe<PageBlocksTrainersTrainerListMutation>>>;
};

export type PageBlocksSponsorsSponsorListMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksSponsorsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  sponsorList?: InputMaybe<Array<InputMaybe<PageBlocksSponsorsSponsorListMutation>>>;
};

export type PageBlocksBenefitsItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksBenefitsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PageBlocksBenefitsItemsMutation>>>;
};

export type PageBlocksMutation = {
  about?: InputMaybe<PageBlocksAboutMutation>;
  values?: InputMaybe<PageBlocksValuesMutation>;
  membership?: InputMaybe<PageBlocksMembershipMutation>;
  trainers?: InputMaybe<PageBlocksTrainersMutation>;
  sponsors?: InputMaybe<PageBlocksSponsorsMutation>;
  benefits?: InputMaybe<PageBlocksBenefitsMutation>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<PageBlocksMutation>>>;
};

export type HeroMutation = {
  welcomeText?: InputMaybe<Scalars['String']['input']>;
  highlightedText?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
  backgroundVideo?: InputMaybe<Scalars['String']['input']>;
};

export type StyretBlocksAboutMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type StyretBlocksMutation = {
  about?: InputMaybe<StyretBlocksAboutMutation>;
};

export type StyretMembersMutation = {
  role?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type StyretCommitteesPeopleMutation = {
  role?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type StyretCommitteesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  people?: InputMaybe<Array<InputMaybe<StyretCommitteesPeopleMutation>>>;
};

export type StyretMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<StyretBlocksMutation>>>;
  members?: InputMaybe<Array<InputMaybe<StyretMembersMutation>>>;
  committees?: InputMaybe<Array<InputMaybe<StyretCommitteesMutation>>>;
};

export type OrganisasjonsplanMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type NewsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SponsorerBlocksAboutMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type SponsorerBlocksBenefitsItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type SponsorerBlocksBenefitsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<SponsorerBlocksBenefitsItemsMutation>>>;
};

export type SponsorerBlocksSponsorsSponsorListMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type SponsorerBlocksSponsorsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  sponsorList?: InputMaybe<Array<InputMaybe<SponsorerBlocksSponsorsSponsorListMutation>>>;
};

export type SponsorerBlocksMutation = {
  about?: InputMaybe<SponsorerBlocksAboutMutation>;
  benefits?: InputMaybe<SponsorerBlocksBenefitsMutation>;
  sponsors?: InputMaybe<SponsorerBlocksSponsorsMutation>;
};

export type SponsorerMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<SponsorerBlocksMutation>>>;
};

export type MedlemskapBlocksMembershipMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  linkUrl?: InputMaybe<Scalars['String']['input']>;
  extraInfo?: InputMaybe<Scalars['String']['input']>;
};

export type MedlemskapBlocksAboutMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type MedlemskapBlocksMutation = {
  membership?: InputMaybe<MedlemskapBlocksMembershipMutation>;
  about?: InputMaybe<MedlemskapBlocksAboutMutation>;
};

export type MedlemskapMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<MedlemskapBlocksMutation>>>;
};

export type OmOssBlocksAboutMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  video?: InputMaybe<Scalars['String']['input']>;
};

export type OmOssBlocksValuesItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type OmOssBlocksValuesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  variant?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<OmOssBlocksValuesItemsMutation>>>;
};

export type OmOssBlocksTrainersTrainerListMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
};

export type OmOssBlocksTrainersMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  trainerList?: InputMaybe<Array<InputMaybe<OmOssBlocksTrainersTrainerListMutation>>>;
};

export type OmOssBlocksMutation = {
  about?: InputMaybe<OmOssBlocksAboutMutation>;
  values?: InputMaybe<OmOssBlocksValuesMutation>;
  trainers?: InputMaybe<OmOssBlocksTrainersMutation>;
};

export type OmOssMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<OmOssBlocksMutation>>>;
};

export type ContactMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalNavMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalMutation = {
  clubName?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  nav?: InputMaybe<Array<InputMaybe<GlobalNavMutation>>>;
  footerDescription?: InputMaybe<Scalars['String']['input']>;
  footerEmail?: InputMaybe<Scalars['String']['input']>;
  footerPhone?: InputMaybe<Scalars['String']['input']>;
  footerAddress?: InputMaybe<Scalars['String']['input']>;
};

export type PagePartsFragment = { __typename: 'Page', title: string, description?: string | null, blocks?: Array<{ __typename: 'PageBlocksAbout', title?: string | null, body?: string | null, image?: string | null } | { __typename: 'PageBlocksValues', title?: string | null, description?: string | null, variant?: string | null, image?: string | null, items?: Array<{ __typename: 'PageBlocksValuesItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | { __typename: 'PageBlocksMembership', title?: string | null, description?: string | null, linkUrl?: string | null } | { __typename: 'PageBlocksTrainers', title?: string | null, trainerList?: Array<{ __typename: 'PageBlocksTrainersTrainerList', name?: string | null, role?: string | null, image?: string | null, bio?: string | null } | null> | null } | { __typename: 'PageBlocksSponsors', title?: string | null, sponsorList?: Array<{ __typename: 'PageBlocksSponsorsSponsorList', name?: string | null, logo?: string | null, url?: string | null } | null> | null } | { __typename: 'PageBlocksBenefits', title?: string | null, items?: Array<{ __typename: 'PageBlocksBenefitsItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | null> | null };

export type HeroPartsFragment = { __typename: 'Hero', welcomeText?: string | null, highlightedText?: string | null, description?: string | null, backgroundImage?: string | null, backgroundVideo?: string | null };

export type StyretPartsFragment = { __typename: 'Styret', title?: string | null, description?: any | null, blocks?: Array<{ __typename: 'StyretBlocksAbout', title?: string | null, body?: string | null } | null> | null, members?: Array<{ __typename: 'StyretMembers', role?: string | null, name?: string | null, image?: string | null } | null> | null, committees?: Array<{ __typename: 'StyretCommittees', name?: string | null, people?: Array<{ __typename: 'StyretCommitteesPeople', role?: string | null, name?: string | null } | null> | null } | null> | null };

export type OrganisasjonsplanPartsFragment = { __typename: 'Organisasjonsplan', title: string, body?: any | null };

export type NewsPartsFragment = { __typename: 'News', title: string, date: string, category?: string | null, image?: string | null, description?: string | null, body?: any | null };

export type SponsorerPartsFragment = { __typename: 'Sponsorer', title: string, blocks?: Array<{ __typename: 'SponsorerBlocksAbout', title?: string | null, body?: string | null, image?: string | null } | { __typename: 'SponsorerBlocksBenefits', title?: string | null, items?: Array<{ __typename: 'SponsorerBlocksBenefitsItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | { __typename: 'SponsorerBlocksSponsors', title?: string | null, sponsorList?: Array<{ __typename: 'SponsorerBlocksSponsorsSponsorList', name?: string | null, logo?: string | null, url?: string | null } | null> | null } | null> | null };

export type MedlemskapPartsFragment = { __typename: 'Medlemskap', title: string, blocks?: Array<{ __typename: 'MedlemskapBlocksMembership', title?: string | null, description?: string | null, linkUrl?: string | null, extraInfo?: string | null } | { __typename: 'MedlemskapBlocksAbout', title?: string | null, body?: string | null, image?: string | null } | null> | null };

export type OmOssPartsFragment = { __typename: 'OmOss', title: string, description?: string | null, blocks?: Array<{ __typename: 'OmOssBlocksAbout', title?: string | null, body?: string | null, image?: string | null, video?: string | null } | { __typename: 'OmOssBlocksValues', title?: string | null, description?: string | null, variant?: string | null, image?: string | null, items?: Array<{ __typename: 'OmOssBlocksValuesItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | { __typename: 'OmOssBlocksTrainers', title?: string | null, trainerList?: Array<{ __typename: 'OmOssBlocksTrainersTrainerList', name?: string | null, role?: string | null, image?: string | null, bio?: string | null } | null> | null } | null> | null };

export type ContactPartsFragment = { __typename: 'Contact', email?: string | null, phone?: string | null, address?: string | null, facebook?: string | null, instagram?: string | null, image?: string | null };

export type GlobalPartsFragment = { __typename: 'Global', clubName?: string | null, logo?: string | null, footerDescription?: string | null, footerEmail?: string | null, footerPhone?: string | null, footerAddress?: string | null, nav?: Array<{ __typename: 'GlobalNav', label?: string | null, href?: string | null } | null> | null };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PageBlocksAbout', title?: string | null, body?: string | null, image?: string | null } | { __typename: 'PageBlocksValues', title?: string | null, description?: string | null, variant?: string | null, image?: string | null, items?: Array<{ __typename: 'PageBlocksValuesItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | { __typename: 'PageBlocksMembership', title?: string | null, description?: string | null, linkUrl?: string | null } | { __typename: 'PageBlocksTrainers', title?: string | null, trainerList?: Array<{ __typename: 'PageBlocksTrainersTrainerList', name?: string | null, role?: string | null, image?: string | null, bio?: string | null } | null> | null } | { __typename: 'PageBlocksSponsors', title?: string | null, sponsorList?: Array<{ __typename: 'PageBlocksSponsorsSponsorList', name?: string | null, logo?: string | null, url?: string | null } | null> | null } | { __typename: 'PageBlocksBenefits', title?: string | null, items?: Array<{ __typename: 'PageBlocksBenefitsItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | null> | null } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PageBlocksAbout', title?: string | null, body?: string | null, image?: string | null } | { __typename: 'PageBlocksValues', title?: string | null, description?: string | null, variant?: string | null, image?: string | null, items?: Array<{ __typename: 'PageBlocksValuesItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | { __typename: 'PageBlocksMembership', title?: string | null, description?: string | null, linkUrl?: string | null } | { __typename: 'PageBlocksTrainers', title?: string | null, trainerList?: Array<{ __typename: 'PageBlocksTrainersTrainerList', name?: string | null, role?: string | null, image?: string | null, bio?: string | null } | null> | null } | { __typename: 'PageBlocksSponsors', title?: string | null, sponsorList?: Array<{ __typename: 'PageBlocksSponsorsSponsorList', name?: string | null, logo?: string | null, url?: string | null } | null> | null } | { __typename: 'PageBlocksBenefits', title?: string | null, items?: Array<{ __typename: 'PageBlocksBenefitsItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type HeroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HeroQuery = { __typename?: 'Query', hero: { __typename: 'Hero', id: string, welcomeText?: string | null, highlightedText?: string | null, description?: string | null, backgroundImage?: string | null, backgroundVideo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HeroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
}>;


export type HeroConnectionQuery = { __typename?: 'Query', heroConnection: { __typename?: 'HeroConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HeroConnectionEdges', cursor: string, node?: { __typename: 'Hero', id: string, welcomeText?: string | null, highlightedText?: string | null, description?: string | null, backgroundImage?: string | null, backgroundVideo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type StyretQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StyretQuery = { __typename?: 'Query', styret: { __typename: 'Styret', id: string, title?: string | null, description?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'StyretBlocksAbout', title?: string | null, body?: string | null } | null> | null, members?: Array<{ __typename: 'StyretMembers', role?: string | null, name?: string | null, image?: string | null } | null> | null, committees?: Array<{ __typename: 'StyretCommittees', name?: string | null, people?: Array<{ __typename: 'StyretCommitteesPeople', role?: string | null, name?: string | null } | null> | null } | null> | null } };

export type StyretConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StyretFilter>;
}>;


export type StyretConnectionQuery = { __typename?: 'Query', styretConnection: { __typename?: 'StyretConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StyretConnectionEdges', cursor: string, node?: { __typename: 'Styret', id: string, title?: string | null, description?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'StyretBlocksAbout', title?: string | null, body?: string | null } | null> | null, members?: Array<{ __typename: 'StyretMembers', role?: string | null, name?: string | null, image?: string | null } | null> | null, committees?: Array<{ __typename: 'StyretCommittees', name?: string | null, people?: Array<{ __typename: 'StyretCommitteesPeople', role?: string | null, name?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type OrganisasjonsplanQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type OrganisasjonsplanQuery = { __typename?: 'Query', organisasjonsplan: { __typename: 'Organisasjonsplan', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type OrganisasjonsplanConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OrganisasjonsplanFilter>;
}>;


export type OrganisasjonsplanConnectionQuery = { __typename?: 'Query', organisasjonsplanConnection: { __typename?: 'OrganisasjonsplanConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'OrganisasjonsplanConnectionEdges', cursor: string, node?: { __typename: 'Organisasjonsplan', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NewsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NewsQuery = { __typename?: 'Query', news: { __typename: 'News', id: string, title: string, date: string, category?: string | null, image?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NewsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
}>;


export type NewsConnectionQuery = { __typename?: 'Query', newsConnection: { __typename?: 'NewsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NewsConnectionEdges', cursor: string, node?: { __typename: 'News', id: string, title: string, date: string, category?: string | null, image?: string | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SponsorerQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SponsorerQuery = { __typename?: 'Query', sponsorer: { __typename: 'Sponsorer', id: string, title: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'SponsorerBlocksAbout', title?: string | null, body?: string | null, image?: string | null } | { __typename: 'SponsorerBlocksBenefits', title?: string | null, items?: Array<{ __typename: 'SponsorerBlocksBenefitsItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | { __typename: 'SponsorerBlocksSponsors', title?: string | null, sponsorList?: Array<{ __typename: 'SponsorerBlocksSponsorsSponsorList', name?: string | null, logo?: string | null, url?: string | null } | null> | null } | null> | null } };

export type SponsorerConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SponsorerFilter>;
}>;


export type SponsorerConnectionQuery = { __typename?: 'Query', sponsorerConnection: { __typename?: 'SponsorerConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SponsorerConnectionEdges', cursor: string, node?: { __typename: 'Sponsorer', id: string, title: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'SponsorerBlocksAbout', title?: string | null, body?: string | null, image?: string | null } | { __typename: 'SponsorerBlocksBenefits', title?: string | null, items?: Array<{ __typename: 'SponsorerBlocksBenefitsItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | { __typename: 'SponsorerBlocksSponsors', title?: string | null, sponsorList?: Array<{ __typename: 'SponsorerBlocksSponsorsSponsorList', name?: string | null, logo?: string | null, url?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type MedlemskapQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MedlemskapQuery = { __typename?: 'Query', medlemskap: { __typename: 'Medlemskap', id: string, title: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'MedlemskapBlocksMembership', title?: string | null, description?: string | null, linkUrl?: string | null, extraInfo?: string | null } | { __typename: 'MedlemskapBlocksAbout', title?: string | null, body?: string | null, image?: string | null } | null> | null } };

export type MedlemskapConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MedlemskapFilter>;
}>;


export type MedlemskapConnectionQuery = { __typename?: 'Query', medlemskapConnection: { __typename?: 'MedlemskapConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MedlemskapConnectionEdges', cursor: string, node?: { __typename: 'Medlemskap', id: string, title: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'MedlemskapBlocksMembership', title?: string | null, description?: string | null, linkUrl?: string | null, extraInfo?: string | null } | { __typename: 'MedlemskapBlocksAbout', title?: string | null, body?: string | null, image?: string | null } | null> | null } | null } | null> | null } };

export type OmOssQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type OmOssQuery = { __typename?: 'Query', omOss: { __typename: 'OmOss', id: string, title: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'OmOssBlocksAbout', title?: string | null, body?: string | null, image?: string | null, video?: string | null } | { __typename: 'OmOssBlocksValues', title?: string | null, description?: string | null, variant?: string | null, image?: string | null, items?: Array<{ __typename: 'OmOssBlocksValuesItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | { __typename: 'OmOssBlocksTrainers', title?: string | null, trainerList?: Array<{ __typename: 'OmOssBlocksTrainersTrainerList', name?: string | null, role?: string | null, image?: string | null, bio?: string | null } | null> | null } | null> | null } };

export type OmOssConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OmOssFilter>;
}>;


export type OmOssConnectionQuery = { __typename?: 'Query', omOssConnection: { __typename?: 'OmOssConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'OmOssConnectionEdges', cursor: string, node?: { __typename: 'OmOss', id: string, title: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'OmOssBlocksAbout', title?: string | null, body?: string | null, image?: string | null, video?: string | null } | { __typename: 'OmOssBlocksValues', title?: string | null, description?: string | null, variant?: string | null, image?: string | null, items?: Array<{ __typename: 'OmOssBlocksValuesItems', title?: string | null, text?: string | null, icon?: string | null } | null> | null } | { __typename: 'OmOssBlocksTrainers', title?: string | null, trainerList?: Array<{ __typename: 'OmOssBlocksTrainersTrainerList', name?: string | null, role?: string | null, image?: string | null, bio?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, email?: string | null, phone?: string | null, address?: string | null, facebook?: string | null, instagram?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, email?: string | null, phone?: string | null, address?: string | null, facebook?: string | null, instagram?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GlobalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlobalQuery = { __typename?: 'Query', global: { __typename: 'Global', id: string, clubName?: string | null, logo?: string | null, footerDescription?: string | null, footerEmail?: string | null, footerPhone?: string | null, footerAddress?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: Array<{ __typename: 'GlobalNav', label?: string | null, href?: string | null } | null> | null } };

export type GlobalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
}>;


export type GlobalConnectionQuery = { __typename?: 'Query', globalConnection: { __typename?: 'GlobalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalConnectionEdges', cursor: string, node?: { __typename: 'Global', id: string, clubName?: string | null, logo?: string | null, footerDescription?: string | null, footerEmail?: string | null, footerPhone?: string | null, footerAddress?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: Array<{ __typename: 'GlobalNav', label?: string | null, href?: string | null } | null> | null } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  description
  blocks {
    __typename
    ... on PageBlocksAbout {
      title
      body
      image
    }
    ... on PageBlocksValues {
      title
      description
      variant
      image
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on PageBlocksMembership {
      title
      description
      linkUrl
    }
    ... on PageBlocksTrainers {
      title
      trainerList {
        __typename
        name
        role
        image
        bio
      }
    }
    ... on PageBlocksSponsors {
      title
      sponsorList {
        __typename
        name
        logo
        url
      }
    }
    ... on PageBlocksBenefits {
      title
      items {
        __typename
        title
        text
        icon
      }
    }
  }
}
    `;
export const HeroPartsFragmentDoc = gql`
    fragment HeroParts on Hero {
  __typename
  welcomeText
  highlightedText
  description
  backgroundImage
  backgroundVideo
}
    `;
export const StyretPartsFragmentDoc = gql`
    fragment StyretParts on Styret {
  __typename
  title
  description
  blocks {
    __typename
    ... on StyretBlocksAbout {
      title
      body
    }
  }
  members {
    __typename
    role
    name
    image
  }
  committees {
    __typename
    name
    people {
      __typename
      role
      name
    }
  }
}
    `;
export const OrganisasjonsplanPartsFragmentDoc = gql`
    fragment OrganisasjonsplanParts on Organisasjonsplan {
  __typename
  title
  body
}
    `;
export const NewsPartsFragmentDoc = gql`
    fragment NewsParts on News {
  __typename
  title
  date
  category
  image
  description
  body
}
    `;
export const SponsorerPartsFragmentDoc = gql`
    fragment SponsorerParts on Sponsorer {
  __typename
  title
  blocks {
    __typename
    ... on SponsorerBlocksAbout {
      title
      body
      image
    }
    ... on SponsorerBlocksBenefits {
      title
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on SponsorerBlocksSponsors {
      title
      sponsorList {
        __typename
        name
        logo
        url
      }
    }
  }
}
    `;
export const MedlemskapPartsFragmentDoc = gql`
    fragment MedlemskapParts on Medlemskap {
  __typename
  title
  blocks {
    __typename
    ... on MedlemskapBlocksMembership {
      title
      description
      linkUrl
      extraInfo
    }
    ... on MedlemskapBlocksAbout {
      title
      body
      image
    }
  }
}
    `;
export const OmOssPartsFragmentDoc = gql`
    fragment OmOssParts on OmOss {
  __typename
  title
  description
  blocks {
    __typename
    ... on OmOssBlocksAbout {
      title
      body
      image
      video
    }
    ... on OmOssBlocksValues {
      title
      description
      variant
      image
      items {
        __typename
        title
        text
        icon
      }
    }
    ... on OmOssBlocksTrainers {
      title
      trainerList {
        __typename
        name
        role
        image
        bio
      }
    }
  }
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  email
  phone
  address
  facebook
  instagram
  image
}
    `;
export const GlobalPartsFragmentDoc = gql`
    fragment GlobalParts on Global {
  __typename
  clubName
  logo
  nav {
    __typename
    label
    href
  }
  footerDescription
  footerEmail
  footerPhone
  footerAddress
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const HeroDocument = gql`
    query hero($relativePath: String!) {
  hero(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeroParts
  }
}
    ${HeroPartsFragmentDoc}`;
export const HeroConnectionDocument = gql`
    query heroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeroFilter) {
  heroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeroParts
      }
    }
  }
}
    ${HeroPartsFragmentDoc}`;
export const StyretDocument = gql`
    query styret($relativePath: String!) {
  styret(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StyretParts
  }
}
    ${StyretPartsFragmentDoc}`;
export const StyretConnectionDocument = gql`
    query styretConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StyretFilter) {
  styretConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StyretParts
      }
    }
  }
}
    ${StyretPartsFragmentDoc}`;
export const OrganisasjonsplanDocument = gql`
    query organisasjonsplan($relativePath: String!) {
  organisasjonsplan(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OrganisasjonsplanParts
  }
}
    ${OrganisasjonsplanPartsFragmentDoc}`;
export const OrganisasjonsplanConnectionDocument = gql`
    query organisasjonsplanConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OrganisasjonsplanFilter) {
  organisasjonsplanConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OrganisasjonsplanParts
      }
    }
  }
}
    ${OrganisasjonsplanPartsFragmentDoc}`;
export const NewsDocument = gql`
    query news($relativePath: String!) {
  news(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NewsParts
  }
}
    ${NewsPartsFragmentDoc}`;
export const NewsConnectionDocument = gql`
    query newsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NewsFilter) {
  newsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NewsParts
      }
    }
  }
}
    ${NewsPartsFragmentDoc}`;
export const SponsorerDocument = gql`
    query sponsorer($relativePath: String!) {
  sponsorer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SponsorerParts
  }
}
    ${SponsorerPartsFragmentDoc}`;
export const SponsorerConnectionDocument = gql`
    query sponsorerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SponsorerFilter) {
  sponsorerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SponsorerParts
      }
    }
  }
}
    ${SponsorerPartsFragmentDoc}`;
export const MedlemskapDocument = gql`
    query medlemskap($relativePath: String!) {
  medlemskap(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MedlemskapParts
  }
}
    ${MedlemskapPartsFragmentDoc}`;
export const MedlemskapConnectionDocument = gql`
    query medlemskapConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MedlemskapFilter) {
  medlemskapConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MedlemskapParts
      }
    }
  }
}
    ${MedlemskapPartsFragmentDoc}`;
export const OmOssDocument = gql`
    query omOss($relativePath: String!) {
  omOss(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OmOssParts
  }
}
    ${OmOssPartsFragmentDoc}`;
export const OmOssConnectionDocument = gql`
    query omOssConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OmOssFilter) {
  omOssConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OmOssParts
      }
    }
  }
}
    ${OmOssPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const GlobalDocument = gql`
    query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const GlobalConnectionDocument = gql`
    query globalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalFilter) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalParts
      }
    }
  }
}
    ${GlobalPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    hero(variables: HeroQueryVariables, options?: C): Promise<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}> {
        return requester<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}, HeroQueryVariables>(HeroDocument, variables, options);
      },
    heroConnection(variables?: HeroConnectionQueryVariables, options?: C): Promise<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}> {
        return requester<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}, HeroConnectionQueryVariables>(HeroConnectionDocument, variables, options);
      },
    styret(variables: StyretQueryVariables, options?: C): Promise<{data: StyretQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StyretQueryVariables, query: string}> {
        return requester<{data: StyretQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StyretQueryVariables, query: string}, StyretQueryVariables>(StyretDocument, variables, options);
      },
    styretConnection(variables?: StyretConnectionQueryVariables, options?: C): Promise<{data: StyretConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StyretConnectionQueryVariables, query: string}> {
        return requester<{data: StyretConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StyretConnectionQueryVariables, query: string}, StyretConnectionQueryVariables>(StyretConnectionDocument, variables, options);
      },
    organisasjonsplan(variables: OrganisasjonsplanQueryVariables, options?: C): Promise<{data: OrganisasjonsplanQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OrganisasjonsplanQueryVariables, query: string}> {
        return requester<{data: OrganisasjonsplanQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OrganisasjonsplanQueryVariables, query: string}, OrganisasjonsplanQueryVariables>(OrganisasjonsplanDocument, variables, options);
      },
    organisasjonsplanConnection(variables?: OrganisasjonsplanConnectionQueryVariables, options?: C): Promise<{data: OrganisasjonsplanConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OrganisasjonsplanConnectionQueryVariables, query: string}> {
        return requester<{data: OrganisasjonsplanConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OrganisasjonsplanConnectionQueryVariables, query: string}, OrganisasjonsplanConnectionQueryVariables>(OrganisasjonsplanConnectionDocument, variables, options);
      },
    news(variables: NewsQueryVariables, options?: C): Promise<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}> {
        return requester<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}, NewsQueryVariables>(NewsDocument, variables, options);
      },
    newsConnection(variables?: NewsConnectionQueryVariables, options?: C): Promise<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}> {
        return requester<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}, NewsConnectionQueryVariables>(NewsConnectionDocument, variables, options);
      },
    sponsorer(variables: SponsorerQueryVariables, options?: C): Promise<{data: SponsorerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorerQueryVariables, query: string}> {
        return requester<{data: SponsorerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorerQueryVariables, query: string}, SponsorerQueryVariables>(SponsorerDocument, variables, options);
      },
    sponsorerConnection(variables?: SponsorerConnectionQueryVariables, options?: C): Promise<{data: SponsorerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorerConnectionQueryVariables, query: string}> {
        return requester<{data: SponsorerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorerConnectionQueryVariables, query: string}, SponsorerConnectionQueryVariables>(SponsorerConnectionDocument, variables, options);
      },
    medlemskap(variables: MedlemskapQueryVariables, options?: C): Promise<{data: MedlemskapQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MedlemskapQueryVariables, query: string}> {
        return requester<{data: MedlemskapQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MedlemskapQueryVariables, query: string}, MedlemskapQueryVariables>(MedlemskapDocument, variables, options);
      },
    medlemskapConnection(variables?: MedlemskapConnectionQueryVariables, options?: C): Promise<{data: MedlemskapConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MedlemskapConnectionQueryVariables, query: string}> {
        return requester<{data: MedlemskapConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MedlemskapConnectionQueryVariables, query: string}, MedlemskapConnectionQueryVariables>(MedlemskapConnectionDocument, variables, options);
      },
    omOss(variables: OmOssQueryVariables, options?: C): Promise<{data: OmOssQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OmOssQueryVariables, query: string}> {
        return requester<{data: OmOssQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OmOssQueryVariables, query: string}, OmOssQueryVariables>(OmOssDocument, variables, options);
      },
    omOssConnection(variables?: OmOssConnectionQueryVariables, options?: C): Promise<{data: OmOssConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OmOssConnectionQueryVariables, query: string}> {
        return requester<{data: OmOssConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OmOssConnectionQueryVariables, query: string}, OmOssConnectionQueryVariables>(OmOssConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      },
    global(variables: GlobalQueryVariables, options?: C): Promise<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}> {
        return requester<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}, GlobalQueryVariables>(GlobalDocument, variables, options);
      },
    globalConnection(variables?: GlobalConnectionQueryVariables, options?: C): Promise<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}, GlobalConnectionQueryVariables>(GlobalConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/810c085c-dd16-47c3-8ca2-865f4019e4ca/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  